services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - node_modules:/app/frontend/node_modules
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
volumes:
  node_modules:
